=== hcarlUnamur/TechnoWeb/src/RessourcesInPut/records.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT records (medical-record|medicine)*>
<!ELEMENT medical-record (patient-id, employee-id, arriving-date, release-date, medical-data-acquisition-method, disease-recognition-date, type)>
<!ATTLIST medical-record record-id ID #REQUIRED medicine-id IDREFS #REQUIRED>
<!ELEMENT patient-id (#PCDATA)>
<!ELEMENT employee-id (#PCDATA)>
<!ELEMENT arriving-date (#PCDATA)>
<!ELEMENT release-date (#PCDATA)>
<!ELEMENT medical-data-acquisition-method (#PCDATA)>
<!ELEMENT disease-recognition-date (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT medicine (name, miligram, age, side-effects)>
<!ATTLIST medicine medicine-id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT miligram (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT side-effects (#PCDATA)>

=== hcarlUnamur/TechnoWeb/src/RessourcesInPut/records.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE records SYSTEM "records.dtd" >
<records>
	<medical-record record-id="Rec1" medicine-id="med-7 med-6 med-8">
		<patient-id>idvalue0</patient-id>
		<employee-id>EMP-1</employee-id>
		<arriving-date>21-02-1999</arriving-date>
		<release-date>23-02-1999</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>22-02-1999</disease-recognition-date>
		<type>Malaria</type>
	</medical-record>
	<medical-record record-id="Rec2" medicine-id="med-2 med-6">
		<patient-id>idvalue0</patient-id>
		<employee-id>EMP-2</employee-id>
		<arriving-date>13-08-2000</arriving-date>
		<release-date>13-08-2000</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>13-08-2000</disease-recognition-date>
		<type>Heart Disease</type>
	</medical-record>
	<medical-record record-id="Rec3" medicine-id="med-4 med-6 med-8">
		<patient-id>idvalue2</patient-id>
		<employee-id>EMP-1</employee-id>
		<arriving-date>21-02-1999</arriving-date>
		<release-date>23-02-1999</release-date>
		<medical-data-acquisition-method>physical exam</medical-data-acquisition-method>
		<disease-recognition-date>22-02-1999</disease-recognition-date>
		<type>Bird Flu</type>
	</medical-record>
	<medical-record record-id="Rec4" medicine-id="med-5 med-7 med-8">
		<patient-id>idvalue1</patient-id>
		<employee-id>EMP-3</employee-id>
		<arriving-date>21-02-2009</arriving-date>
		<release-date>27-05-2009</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>21-02-2009</disease-recognition-date>
		<type>Skin cancer</type>
	</medical-record>
	<medical-record record-id="Rec5" medicine-id="med-1 med-6 med-8">
		<patient-id>idvalue11</patient-id>
		<employee-id>EMP-2</employee-id>
		<arriving-date>21-02-2009</arriving-date>
		<release-date>21-02-2009</release-date>
		<medical-data-acquisition-method>Echocardiography</medical-data-acquisition-method>
		<disease-recognition-date>21-02-2009</disease-recognition-date>
		<type>Kawasaki</type>
	</medical-record>
	<medical-record record-id="Rec6" medicine-id="med-6 med-7 med-8">
		<patient-id>idvalue3</patient-id>
		<employee-id>EMP-4</employee-id>
		<arriving-date>21-02-2010</arriving-date>
		<release-date>29-02-2010</release-date>
		<medical-data-acquisition-method>physical exam</medical-data-acquisition-method>
		<disease-recognition-date>22-02-2010</disease-recognition-date>
		<type>Flu (virus)</type>
	</medical-record>
	<medical-record record-id="Rec7" medicine-id="med-6 med-7 med-8">
		<patient-id>idvalue4</patient-id>
		<employee-id>EMP-1</employee-id>
		<arriving-date>27-02-2011</arriving-date>
		<release-date>02-03-2011</release-date>
		<medical-data-acquisition-method>physical exam</medical-data-acquisition-method>
		<disease-recognition-date>28-02-2011</disease-recognition-date>
		<type>Flu (virus)</type>
	</medical-record>

	<medical-record record-id="Rec8" medicine-id="med-1 med-6 med-8">
		<patient-id>idvalue12</patient-id>
		<employee-id>EMP-1</employee-id>
		<arriving-date>27-02-2011</arriving-date>
		<release-date>02-03-2011</release-date>
		<medical-data-acquisition-method>Echocardiography</medical-data-acquisition-method>
		<disease-recognition-date>28-02-2011</disease-recognition-date>
		<type>Kawasaki</type>
	</medical-record>

	<medical-record record-id="Rec9" medicine-id="med-1 med-6 med-8">
		<patient-id>idvalue9</patient-id>
		<employee-id>EMP-1</employee-id>
		<arriving-date>27-02-2012</arriving-date>
		<release-date>05-03-2012</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>28-02-2012</disease-recognition-date>
		<type>Kawasaki</type>
	</medical-record>
	<medical-record record-id="Rec10" medicine-id="med-5 med-7 med-8">
		<patient-id>idvalue5</patient-id>
		<employee-id>EMP-4</employee-id>
		<arriving-date>27-02-2011</arriving-date>
		<release-date>02-03-2011</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>28-02-2011</disease-recognition-date>
		<type>Skin cancer</type>
	</medical-record>
	<medical-record record-id="Rec11" medicine-id="med-6 med-7 med-8">
		<patient-id>idvalue5</patient-id>
		<employee-id>EMP-1</employee-id>
		<arriving-date>27-09-2011</arriving-date>
		<release-date>02-10-2011</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>28-09-2011</disease-recognition-date>
		<type>tension headache</type>
	</medical-record>
	<medical-record record-id="Rec12" medicine-id="med-4 med-6 med-8">
		<patient-id>idvalue6</patient-id>
		<employee-id>EMP-2</employee-id>
		<arriving-date>20-02-2011</arriving-date>
		<release-date>02-03-2011</release-date>
		<medical-data-acquisition-method>physical exam</medical-data-acquisition-method>
		<disease-recognition-date>28-02-2011</disease-recognition-date>
		<type>Bird Flu</type>
	</medical-record>	
	<medical-record record-id="Rec13" medicine-id="med-6 med-7 med-8">
		<patient-id>idvalue7</patient-id>
		<employee-id>EMP-1</employee-id>
		<arriving-date>27-02-2012</arriving-date>
		<release-date>02-03-2012</release-date>
		<medical-data-acquisition-method>physical exam</medical-data-acquisition-method>
		<disease-recognition-date>28-02-2012</disease-recognition-date>
		<type>Flu (virus)</type>
	</medical-record>
    <medical-record record-id="Rec14" medicine-id="med-5 med-7 med-8">
		<patient-id>idvalue10</patient-id>
		<employee-id>EMP-2</employee-id>
		<arriving-date>21-02-2009</arriving-date>
		<release-date>27-05-2009</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>21-02-2009</disease-recognition-date>
		<type>Skin cancer</type>
	</medical-record>	
	<medical-record record-id="Rec15" medicine-id="med-1 med-6 med-8">
		<patient-id>idvalue8</patient-id>
		<employee-id>EMP-4</employee-id>
		<arriving-date>27-02-2012</arriving-date>
		<release-date>02-03-2012</release-date>
		<medical-data-acquisition-method>blood test</medical-data-acquisition-method>
		<disease-recognition-date>28-02-2012</disease-recognition-date>
		<type>Kawasaki</type>
	</medical-record>	
	<medicine medicine-id="med-1">
		<name>warfarin</name>
		<miligram>200</miligram>
		<age>&lt;10</age>
		<side-effects></side-effects>
	</medicine>
	<medicine medicine-id="med-2">
		<name>Cardiprin</name>
		<miligram>300</miligram>
		<age>&gt;3</age>
		<side-effects></side-effects>
	</medicine>
	<medicine medicine-id="med-3">
		<name>Acidosis Medications</name>
		<miligram>500</miligram>
		<age>&gt;10</age>
		<side-effects></side-effects>
	</medicine>
	<medicine medicine-id="med-4">
		<name>Oseltamivir</name>
		<miligram>500</miligram>
		<age>&gt;5</age>
		<side-effects></side-effects>
	</medicine>
	<medicine medicine-id="med-5">
		<name>Hydrea</name>
		<miligram>500</miligram>
		<age></age>
		<side-effects></side-effects>
	</medicine>
	<medicine medicine-id="med-6">
		<name>Paracetamol</name>
		<miligram>250</miligram>
		<age></age>
		<side-effects></side-effects>
	</medicine>
	<medicine medicine-id="med-7">
		<name>Aspirin</name>
		<miligram>300</miligram>
		<age>&gt;2</age>
		<side-effects></side-effects>
	</medicine>
	<medicine medicine-id="med-8">
		<name>Panadol</name>
		<miligram>300</miligram>
		<age></age>
		<side-effects></side-effects>
	</medicine>
</records>
